version: '3'
services:
    elasticsearch:
        image: blacktop/elasticsearch
        container_name: elastic
        ports:
          - "9200:9200"
        network_mode: bridge
        restart: unless-stopped
    
    kibana:
        links:
          - elasticsearch
        image: blacktop/kibana
        container_name: kibana
        ports:
          - "5601:5601"
        network_mode: bridge
        restart: unless-stopped

    logstash:
        links:
            - elasticsearch
        build:
          context: logstash/
        container_name: logstash
        ports:
             - "5044:5044"
        network_mode: bridge
        restart: unless-stopped